/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.management.system;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Achmad Muchlasin
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        separatorPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        formPanel = new javax.swing.JPanel();
        nameInputPanel = new javax.swing.JPanel();
        firstNamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaDepan = new javax.swing.JTextField();
        lastNamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNamaBelakang = new javax.swing.JTextField();
        otherInputPanel = new javax.swing.JPanel();
        npmPanel = new javax.swing.JPanel();
        npmLabel = new javax.swing.JLabel();
        txtNpm = new javax.swing.JTextField();
        jurusanPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbJurusan = new javax.swing.JComboBox<>();
        alamatPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        phonePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        footerPanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMhs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setMaximumSize(new java.awt.Dimension(1500, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        mainPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        titlePanel.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Student Management System");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mainPanel.add(titlePanel);

        separatorPanel.setPreferredSize(new java.awt.Dimension(400, 10));

        javax.swing.GroupLayout separatorPanelLayout = new javax.swing.GroupLayout(separatorPanel);
        separatorPanel.setLayout(separatorPanelLayout);
        separatorPanelLayout.setHorizontalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(separatorPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        separatorPanelLayout.setVerticalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, separatorPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(separatorPanel);

        formPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        nameInputPanel.setPreferredSize(new java.awt.Dimension(400, 60));

        firstNamePanel.setPreferredSize(new java.awt.Dimension(150, 50));
        firstNamePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel2.setText("Nama Depan");
        firstNamePanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        firstNamePanel.add(txtNamaDepan, java.awt.BorderLayout.CENTER);

        nameInputPanel.add(firstNamePanel);

        lastNamePanel.setPreferredSize(new java.awt.Dimension(150, 50));
        lastNamePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel3.setText("Nama Belakang");
        lastNamePanel.add(jLabel3, java.awt.BorderLayout.NORTH);
        lastNamePanel.add(txtNamaBelakang, java.awt.BorderLayout.CENTER);

        nameInputPanel.add(lastNamePanel);

        formPanel.add(nameInputPanel);

        otherInputPanel.setPreferredSize(new java.awt.Dimension(400, 240));

        npmPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        npmPanel.setLayout(new java.awt.BorderLayout(0, 4));

        npmLabel.setText("NPM");
        npmPanel.add(npmLabel, java.awt.BorderLayout.PAGE_START);
        npmPanel.add(txtNpm, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(npmPanel);

        jurusanPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        jurusanPanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel5.setText("Jurusan");
        jurusanPanel.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        cbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Teknik Informatika", "Teknik Sipil", "Teknik Industri", "Teknik Kelautan" }));
        jurusanPanel.add(cbJurusan, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(jurusanPanel);

        alamatPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        alamatPanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel6.setText("Alamat");
        alamatPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);
        alamatPanel.add(txtAlamat, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(alamatPanel);

        phonePanel.setPreferredSize(new java.awt.Dimension(305, 50));
        phonePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel7.setText("No. Telpon");
        phonePanel.add(jLabel7, java.awt.BorderLayout.PAGE_START);
        phonePanel.add(txtNoTelp, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(phonePanel);

        formPanel.add(otherInputPanel);

        mainPanel.add(formPanel);

        footerPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        actionPanel.setLayout(new java.awt.BorderLayout(5, 5));

        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/add_new_24px.png"))); // NOI18N
        btnTambah.setText("Add");
        btnTambah.setPreferredSize(new java.awt.Dimension(95, 23));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        actionPanel.add(btnTambah, java.awt.BorderLayout.WEST);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/edit_24px.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(95, 33));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        actionPanel.add(btnUpdate, java.awt.BorderLayout.CENTER);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/waste_24px.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(95, 32));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        actionPanel.add(btnDelete, java.awt.BorderLayout.EAST);

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/clear_symbol_24px.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(73, 32));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        actionPanel.add(btnClear, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mainPanel.add(footerPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.WEST);

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setPreferredSize(new java.awt.Dimension(600, 430));
        tablePanel.setLayout(new java.awt.BorderLayout(0, 4));

        tbMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "NPM", "Nama Depan", "Nama Belakang", "Jurusan", "Alamat", "No. Telpon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMhs);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE student SET npm = '" + txtNpm.getText() + "', nama_depan = '" + txtNamaDepan.getText() + "', nama_belakang = '" + txtNamaBelakang.getText() + "', jurusan = '" + cbJurusan.getSelectedItem()+"', alamat = '" + txtAlamat.getText() + "', no_telp = '" + txtNoTelp.getText() + "' WHERE npm = '" + txtNpm.getText() + "'";
            Connection conn = (Connection)Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Data gagal diubah, karena " + e.getMessage());
        }
        loadTable();
        resetForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO student VALUES ('" + txtNpm.getText() + "','" + txtNamaDepan.getText() + "','" + txtNamaBelakang.getText() + "','" + cbJurusan.getSelectedItem() + "','" + txtAlamat.getText() + "','" + txtNoTelp.getText() + "')";
            Connection conn = (Connection)Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ups, data gagal disimpan");
        }
        loadTable();
        resetForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tbMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMhsMouseClicked
        // TODO add your handling code here:
        int row = tbMhs.rowAtPoint(evt.getPoint());
        String npm = tbMhs.getValueAt(row, 1).toString();
        txtNpm.setText(npm);
        String nama_depan = tbMhs.getValueAt(row, 2).toString();
        txtNamaDepan.setText(nama_depan);
        String nama_belakang = tbMhs.getValueAt(row, 3).toString();
        txtNamaBelakang.setText(nama_belakang);
        String jurusan = tbMhs.getValueAt(row, 4).toString();
        cbJurusan.setSelectedItem(jurusan);
        String alamat = tbMhs.getValueAt(row, 5).toString();
        txtAlamat.setText(alamat);
        String telp = tbMhs.getValueAt(row, 6).toString();
        txtNoTelp.setText(telp);
    }//GEN-LAST:event_tbMhsMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM student WHERE npm = '" + txtNpm.getText() + "'";
            Connection conn = (Connection)Config.configDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Data gagal dihapus, karena " + e.getMessage());
        }
        loadTable();
        resetForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnClearActionPerformed
    
    private void loadTable() {
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("NPM");
        model.addColumn("Nama Depan");
        model.addColumn("Nama Belakang");
        model.addColumn("Jurusan");
        model.addColumn("Alamat");
        model.addColumn("No. Telpon");
        
        // load dari database ke table model
        try {
            int no_tb = 1;
            String sql = "SELECT * FROM student";
            Connection conn = (Connection)Config.configDB();
            Statement sttm = conn.createStatement();
            ResultSet rs = sttm.executeQuery(sql);
            while(rs.next()) {
                model.addRow(new Object[]{no_tb++, rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6)});    
            }
            tbMhs.setModel(model);
        } catch (Exception e) {
        }
    }
    
    private void resetForm() {
        txtNpm.setText(null);
        txtNamaDepan.setText(null);
        txtNamaBelakang.setText(null);
        cbJurusan.setSelectedIndex(0);
        txtAlamat.setText(null);
        txtNoTelp.setText(null);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbJurusan;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jurusanPanel;
    private javax.swing.JPanel lastNamePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel nameInputPanel;
    private javax.swing.JLabel npmLabel;
    private javax.swing.JPanel npmPanel;
    private javax.swing.JPanel otherInputPanel;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JPanel separatorPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JTable tbMhs;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNamaBelakang;
    private javax.swing.JTextField txtNamaDepan;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtNpm;
    // End of variables declaration//GEN-END:variables
}
