/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.management.system;

/**
 *
 * @author Achmad Muchlasin
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        separatorPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        formPanel = new javax.swing.JPanel();
        nameInputPanel = new javax.swing.JPanel();
        firstNamePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        lastNamePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        otherInputPanel = new javax.swing.JPanel();
        npmPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jurusanPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        alamatPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        phonePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        footerPanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management System");
        setMaximumSize(new java.awt.Dimension(1500, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        mainPanel.setPreferredSize(new java.awt.Dimension(400, 0));

        titlePanel.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Student Management System");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        mainPanel.add(titlePanel);

        separatorPanel.setPreferredSize(new java.awt.Dimension(400, 10));

        javax.swing.GroupLayout separatorPanelLayout = new javax.swing.GroupLayout(separatorPanel);
        separatorPanel.setLayout(separatorPanelLayout);
        separatorPanelLayout.setHorizontalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(separatorPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        separatorPanelLayout.setVerticalGroup(
            separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, separatorPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(separatorPanel);

        formPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        nameInputPanel.setPreferredSize(new java.awt.Dimension(400, 60));

        firstNamePanel.setPreferredSize(new java.awt.Dimension(150, 50));
        firstNamePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel2.setText("Nama Depan");
        firstNamePanel.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        firstNamePanel.add(jTextField6, java.awt.BorderLayout.CENTER);

        nameInputPanel.add(firstNamePanel);

        lastNamePanel.setPreferredSize(new java.awt.Dimension(150, 50));
        lastNamePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel3.setText("Nama Belakang");
        lastNamePanel.add(jLabel3, java.awt.BorderLayout.NORTH);
        lastNamePanel.add(jTextField7, java.awt.BorderLayout.CENTER);

        nameInputPanel.add(lastNamePanel);

        formPanel.add(nameInputPanel);

        otherInputPanel.setPreferredSize(new java.awt.Dimension(400, 240));

        npmPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        npmPanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel4.setText("NIM");
        npmPanel.add(jLabel4, java.awt.BorderLayout.PAGE_START);
        npmPanel.add(jTextField5, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(npmPanel);

        jurusanPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        jurusanPanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel5.setText("Jurusan");
        jurusanPanel.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Teknik Informatika", "Teknik Sipil", "Teknik Industri", "Teknik Kelautan" }));
        jurusanPanel.add(jComboBox1, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(jurusanPanel);

        alamatPanel.setPreferredSize(new java.awt.Dimension(305, 50));
        alamatPanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel6.setText("Alamat");
        alamatPanel.add(jLabel6, java.awt.BorderLayout.PAGE_START);
        alamatPanel.add(jTextField4, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(alamatPanel);

        phonePanel.setPreferredSize(new java.awt.Dimension(305, 50));
        phonePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel7.setText("No. Telpon");
        phonePanel.add(jLabel7, java.awt.BorderLayout.PAGE_START);
        phonePanel.add(jTextField8, java.awt.BorderLayout.CENTER);

        otherInputPanel.add(phonePanel);

        formPanel.add(otherInputPanel);

        mainPanel.add(formPanel);

        footerPanel.setPreferredSize(new java.awt.Dimension(400, 100));

        actionPanel.setLayout(new java.awt.BorderLayout(0, 5));

        jButton1.setText("Tambah");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 23));
        actionPanel.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(150, 33));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        actionPanel.add(jButton2, java.awt.BorderLayout.EAST);

        jButton4.setText("Delete");
        jButton4.setPreferredSize(new java.awt.Dimension(73, 32));
        actionPanel.add(jButton4, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mainPanel.add(footerPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.WEST);

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setPreferredSize(new java.awt.Dimension(600, 430));
        tablePanel.setLayout(new java.awt.BorderLayout(0, 4));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Depan", "Nama Belakang", "NPM", "Jurusan", "Alamat", "No. Telpon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        tablePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JPanel firstNamePanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel jurusanPanel;
    private javax.swing.JPanel lastNamePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel nameInputPanel;
    private javax.swing.JPanel npmPanel;
    private javax.swing.JPanel otherInputPanel;
    private javax.swing.JPanel phonePanel;
    private javax.swing.JPanel separatorPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
